database:
  host: postgres-hypha
  port: 5432
  user: postgres
  dbname: hypha
  password: mysecretpassword
  sslmode: disable
http:
  port: 8081
  cors-policy:
    allow-origins:
      - "*"
    allow-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    allow-headers:
      - "Origin"
      - "Content-Type"
      - "Accept"
    expose-headers:
      - "Content-Length"
    allow-credentials: true
    max-age: 43200