name: build
on:
  release:
    types: [released]

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract tag name
        id: extract_tag
        shell: bash
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Update package.json version
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          jq --arg version "${{ env.TAG_NAME }}" '.version = $version' package.json > tmp.$$.json && mv tmp.$$.json package.json
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add package.json
          git commit -m "chore: update package.json version to ${{ env.TAG_NAME }}"
          git push origin HEAD:$BRANCH_NAME

  build-push-image:
    runs-on: ubuntu-latest
    needs: update-version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        shell: bash
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:v${{ env.TAG_NAME }}
            ghcr.io/${{ github.repository }}:latest