name: build-push-image
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  build-push-image:
    uses: hypha-rp/actions/.github/workflows/build-push-image.yml@main
    with:
      tags: |
        ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        ghcr.io/${{ github.repository }}:latest