name: build
on:
  release:
    types: [released]

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update version in package.json
        run: |
          jq --arg version "${{ env.TAG_NAME }}" '.version=$version' package.json > package.tmp.json
          mv package.tmp.json package.json

      - name: Update npm lock file
        run: npm install

      - name: Commit updated package.json and lock file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add package.json package-lock.json
          git commit -m "chore: update packaged version to ${{ env.TAG_NAME }}"
          git push origin HEAD:main

  build-push-image:
    runs-on: ubuntu-latest
    needs: update-version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        shell: bash
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:v${{ env.TAG_NAME }}
            ghcr.io/${{ github.repository }}:latest