name: pull-request-checks

on:
    pull_request:
      branches:
        - main

permissions:
  contents: read
  packages: read
  issues: read

jobs:
    build-image:
        uses: hypha-rp/actions/.github/workflows/build-image.yml@main
    
    lint:
        uses: hypha-rp/actions/.github/workflows/node-lint.yml@main
        with:
            node-version: "22.x"