name: pull-request

on:
    pull_request:
      branches:
        - main
        - development

permissions:
  contents: read
  packages: read
  issues: read

jobs:
  build-image:
      runs-on: ubuntu-latest
      steps:
        - name: Build image
          uses: hypha-rp/actions/build-image@main

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: hypha-rp/actions/node-lint@main
