name: release
on:
  push:
    branches:
      - main

permissions:
    contents: write
    issues: write
    pull-requests: write
    id-token: write

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm clean-install

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Authenticate with GitHub App
        id: auth
        run: |
          echo "APP_ID=${{ secrets.APP_ID }}" >> $GITHUB_ENV
          echo "APP_PRIVATE_KEY=${{ secrets.APP_PRIVATE_KEY }}" >> $GITHUB_ENV
          echo "APP_INSTALLATION_ID=${{ secrets.APP_INSTALLATION_ID }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=$(curl -X POST -H \"Authorization: Bearer $(jwt -i $APP_ID -k $APP_PRIVATE_KEY)\" -H \"Accept: application/vnd.github.v3+json\" https://api.github.com/app/installations/$APP_INSTALLATION_ID/access_tokens | jq -r .token)" >> $GITHUB_ENV

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release