name: release
on:
  push:
    branches:
      - main
      - release-workflow
  pull_request:
    branches:
      - main
      - release-workflow

jobs:
  lint:
    uses: hypha-rp/ui/.github/jobs/lint.yml@release-workflow

  build-image:
    needs: lint
    uses: hypha-rp/ui/.github/jobs/build-image.yml@release-workflow

  semantic-release:
    needs: [lint, build-image]
    uses: hypha-rp/ui/.github/jobs/semantic-release.yml@release-workflow