name: release
on:
  push:
    branches:
      - main
      - release-workflow
  pull_request:
    branches:
      - main
      - release-workflow

jobs:
  lint:
    uses: ./.github/jobs/lint.yml

  build-image:
    needs: lint
    uses: ./.github/jobs/build-image.yml

  semantic-release:
    needs: [lint, build-image]
    uses: ./.github/jobs/semantic-release.yml